spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 215MB

  main:
     allow-bean-definition-overriding: 'true'
  jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.MySQL5Dialect
   properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    max_allowed_packet: '2000'
   show-sql: 'true'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    password:
    username: root
    url: jdbc:mysql://localhost:3306/file_upload?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare
    driver-class-name: org.mariadb.jdbc.Driver


upload-dir: ./uploads

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/


management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

security:
  oauth2:
    client:
      client-secret: RobTheRich
      client-id: file-strorage-service
