spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  sleuth:
    enabled: false
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:
        ## USER-SERVICE
        - id: User-service
          uri: lb://User-service
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users**,/api/v1/admin/users/**

        - id: User-service
          uri: lb://User-service
          predicates:
            - Path=/api/v1/users**,/api/v1/admin/users/**,/api/v1/auth/**

        ## USSD-HEALTH
        - id: health-ussd
          uri: lb://health-ussd
          predicates:
            - Path=/firstmutual/fmhealth/ussd-live/**

        ## USSD-LIFE
        - id: life-ussd
          uri: lb://life-ussd
          predicates:
            - Path=/firstmutual/life/ussd-live/**

        ## USSD-HOLDINGS
        - id: holdings-ussd
          uri: lb://holdings-ussd
          predicates:
            - Path=/firstmutual/health/ussd-live/**

server:
  port: 1980

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka

security:
  oauth2:
    resource:
      id: holdings-web-service
    client:
      client-id: gateway-service
      client-secret: RobTheRich